### ISSUE TITLE
Unusual behavior of windows binary compiled from source

### ISSUE THREAD

**Issue by jfsoul** [rjhansen/nsrllookup#1]
I followed the command line instructions from README.W32 to compile v1.2.3 from source (using VS2012):

```
cl /O2 /EHsc /Fensrllookup.exe /MT src/*.cc /link ws2_32.lib
```

There aren't any warnings during compilation and executing the binary from the command line against my server appears to work correctly for a quick test with a couple of hashes.  

Unfortunately when I try and run the exact same command through Node.js (as a child process) I get an empty response.  So, a problem with my javascript most likely.  Except that using the exact same Node.js code with either of the Windows binaries downloaded from http://rjhansen.github.io/nsrllookup/ works as expected.  All nsrllookup versions I have used are v1.2.3.

I'm looking into possible issues with on the Node.js side, but I'm wondering whether you could give me details on how you compile the windows binaries, as the provided ones seem to work.  I also noticed that the ones that I compile are significantly smaller in size (less than half).

**Comment by rjhansen** [comment]
I build the Windows versions by cross-compiling from Linux using GNU G++.  Before a release I check to make sure the Visual Studio build instructions still work and that the resulting binary can do some queries, but that's as far as my Microsoft toolchain tests go.
