### ISSUE TITLE
No need to provide autogenerate configure script in git when not providing all necessary files

### ISSUE THREAD

**Issue by joachimmetz** [rjhansen/nsrllookup#3]
FYI running './configure' from a fresh clone results in:

```
/bin/sh: aclocal-1.13: command not found
Makefile:321: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
```

To fix this I ran:

```
autoreconf -fiv
```

However that command will generate `./configure`, and other files.

I opt to just remove `./configure` from the git repo since it is auto-generated anyway and provide a distribution package `make dist` on the github releases page.

**Comment by rjhansen** [comment]
-master isn't meant for people looking for a frustration-free build; they should stick to releases.  This is a "if I remember to, I'll do it".  Leaving the ticket open to remind me to get around to it.

**Comment by joachimmetz** [comment]
> -master isn't meant for people looking for a frustration-free build; they should stick to releases.

Ack, totally agree ;)

**Comment by rjhansen** [comment]
-master is now using a CMake build system.  I'm going to mark this one done, since we no longer use Autotools at all.  :)
