### ISSUE TITLE
Please add server and port defaults to help output

### ISSUE THREAD

**Issue by joachimmetz** [rjhansen/nsrllookup#4]
Current help does not indicates its defaults:

```
/src/nsrllookup -h
nsrllookup for Linux version 1.2.3

nsrllookup [-hvukS] [-U FILE] [-K FILE] [-s SERVER] [-p PORT]

        -h: display this help message
        -v: display version information
        -u: show only unknown hashes (default)
        -k: show only known hashes
        -S: display server status (if possible)
        -U FILE: write unknown hashes to FILE
        -K FILE: write known hashes to FILE
        -s SERVER: connect to a specified nsrlquery server
        -p PORT: connect on a specified port
```

I opt adding the defaults like:

```
        -s SERVER: connect to a specified nsrlquery server, default is "nsrllookup.com"
        -p PORT: connect on a specified port, default is 9120
```

Also ideally make the default information reported by nsrllookup more verbose and have a quiet mode for non-interactive usage.

Currently:

```
echo "5f1363974b106c23ea718e495266c527" | ./src/nsrllookup 
5f1363974b106c23ea718e495266c527
```

This does not tell me which server was queried, and what the result is, if the MD5 exists or not the result is the same. It is not obvious at first to use `-s -p -k`. Hence I opt the default output to be something like:

```
echo "5f1363974b106c23ea718e495266c527" | ./src/nsrllookup 

Server queried: nsrllookup.com:9120
Found: 5f1363974b106c23ea718e495266c527
```

**Comment by rjhansen** [comment]
One request per ticket, please.

Better help text is possible.  Changing the output is a WONTFIX.  nsrllookup is a filter: you throw it a set of hashes and it filters them according to a criteria.  Filter apps do not and should not add anything to the output which doesn't pass the filter.

Consider grep as an example: grep filters what gets fed to it and adds nothing to the output stream.  :)

**Comment by joachimmetz** [comment]
> Changing the output is a WONTFIX.

That is fine, as indicated it's a suggestion.

**Comment by rjhansen** [comment]
Fixed in -master.
