### ISSUE TITLE
cmake -D CMAKE_BUILD_TYPE=Release .

### ISSUE THREAD

**Issue by PointerWild** [rjhansen/nsrllookup#5]
Is it  " cmake -D CMAKE_BUILD_TYPE=Release " ,the order in README.md ,right?
Should it write as " cmake -DCMAKE_BUILD_TYPE=Release  " ?

**Comment by rjhansen** [comment]
Please see [the CMake FAQ](https://gitlab.kitware.com/cmake/community/wikis/FAQ#method-2-use-cmake-d).

Both will work but CMake's official standard uses a space.
