### ISSUE TITLE
What is the input format

### ISSUE THREAD

**Issue by Lyro1** [rjhansen/nsrllookup#6]
I have a list of processes and files with various datas, such as the path of the file, various hash values, some IDs, and others...
But after reading the README file, there seems not to be any kind of required structure for the input file. But I just want to be sure:

Is there any required input format ?

**Comment by rjhansen** [comment]
Well, the README has an example:

```
md5deep -r /path/to/collection > all_hashes.txt
nsrllookup < all_hashes.txt > rds_misses.txt
```

If you look at `md5deep`'s output format, you'll be on the right path.  ;)  Or if you want to take a look at the [code](https://github.com/rjhansen/nsrllookup/blob/bc0423c65398a383f689659986e43f45531d16db/src/nsrllookup.cc#L53)…

Short version: an input line must start with 32 hexadecimal digits, case-insensitive.  Anything after those 32 hexadecimal digits is ignored.

**Comment by Lyro1** [comment]
Perfect, thank you for this precision.
