### ISSUE TITLE
NSRLLOOKUP.COM not working

### ISSUE THREAD

**Issue by q4u2018** [rjhansen/nsrllookup#7]
Hey is this website no longer maintained?  Getting a 503 error when navigating, and nsrllookup is failing.

**Comment by rjhansen** [comment]
Huh.  Works fine for me:

```
rjh@maggie:~$ md5sum foo.txt | nsrllookup
BF2D551747130374A981BE5F971CD6A1
```

`nsrllookup.com` has never had a webpage, or even an Apache instance attached to it — which should explain the 503.

If your problem persists I'd be happy to look into it!
